import type { Metadata } from "next";
import { Bitcount } from "next/font/google";
import "./globals.css";

const bitcount = Bitcount({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bitcount.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
